workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        integrations:
          app_store_connect: AwesomeProjectAuthKey
        environment:
          ios_signing:
            distribution_type: app_store
            bundle_identifier: com.AwesomeProject.awesomeProject
          vars:
            APP_STORE_APPLE_ID: 6608978003
            BUNDLE_ID: "com.AwesomeProject.awesomeProject"
            XCODE_WORKSPACE: "awesomeProject.xcworkspace" # <-- Name of your Xcode workspace
            XCODE_SCHEME: "awesomeProject" # <-- Name of your Xcode scheme
        scripts:
          - name: Install node modules
            script: |
              npm install
          - name: Set Info.plist values
            script: | 
              PLIST=$CM_BUILD_DIR/ios/awesomeProject/Info.plist
              PLIST_BUDDY=/usr/libexec/PlistBuddy
              $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST    
          - name: Install CocoaPods dependencies
            script: |
              cd ios && pod install
          - name: Set up provisioning profile settings on Xcode project
            script: |
              cd ios
              xcode-project use-profiles
          - name: Increment build number
            script: | 
              #!/bin/sh
              cd $CM_BUILD_DIR/ios
              LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
              agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          - name: Build ipa for distribution
            script: | 
              xcode-project build-ipa \
                --workspace "$CM_BUILD_DIR/ios/awesomeProject.xcworkspace" \
                --scheme "awesomeProject"
        artifacts:
          - build/ios/ipa/*.ipa
          - /tmp/xcodebuild_logs/*.log
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
